### ISSUE TITLE
Able to receive non-JSON response (like images or other filetypes)?

### ISSUE THREAD

**Issue by irelandpaul** [apollostack/apollo-client#1045]
I would like to use graphQL and Apollo client to download files. I am trying to keep everything in GraphQL if possible.

I get this error when downloading an image:
"SyntaxError: Unexpected token � in JSON at position 0"

I tried to handle it in Afterware but this error triggers before it hits the Afterware call. 

Any suggestions how to handle this?

**Comment by helfer** [comment]
@irelandpaul if you encode your image with base64 or similar, you can include it in the JSON and then read it out on the client, but I wouldn't generally recommend that except for tiny images. The way to go is to just send the url and have the image or file be served from a separate endpoint, usually a different server/service.

**Comment by thebigredgeek** [comment]
@irelandpaul I'd recommend returning a pointer (url) to the asset in the response, and then fetching that asset from that URL.  As @helfer said above.  Otherwise you have to somehow transmit an entire binary response back to the client and somehow transmute that back into JSON plucking out the values that are non-json compat.  Sounds like a lot of unnecessary work :p

**Comment by helfer** [comment]
I think @thebigredgeek pretty much summed it up. I'll close the issue, but we can reopen if further discussion is needed.
