### ISSUE TITLE
Returning result objects with empty fields omitted

### ISSUE THREAD

**Issue by paralin** [apollostack/apollo-client#1110]
I'm writing a Go GraphQL server right now, and I'm running into the problem that the JSON tags on our structs cause the language to convert the result objects to JSON without any empty fields. For example, if I had the type here:

```
type MyType {
  id: String
  level: Int
}
```

The result (for a basic query) would look like:

```
{"data":{"things":[{"id":"id1"},{"id":"id2","level":3}]},"errors":[]}
```

As you can see the "empty" (`undefined, null, 0, or ""`) fields were omitted. Apollo right now complains because it doesn't find those fields in the result (suggesting the `returnPartialData` option).

Would it be possible to get Apollo to treat omitted fields as just default values?

**Comment by helfer** [comment]
@paralin it seems that your server isn't compliant with the GraphQL spec, which requires those values to be there. Regardless of that, it sounds like your JSON serialization function isn't really working. `null`, `0` and `""` are all semantically meaningful values, they can't just be ignored. I'll close this issue since this problem has to be fixed on the server end of things.
