### ISSUE TITLE
Use monorepo for all the packages related to apollo-client

### ISSUE THREAD

**Issue by wizardzloy** [apollostack/apollo-client#1111]
Sometimes you run into issues that have the scope wider than a single repository (e.g. `react-apollo` + `apollo-client`). In this case, it becomes tricky to find out is there any existing issue filed for that, you have to search through several repositories and also make a choice of where to submit the new one in case it is not yet reported.

Have we ever considered having a [monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md) setup for all the packages built around `apollo-client`? 
What is your opinion on this approach?

**Comment by helfer** [comment]
@wizardzloy we have a monorepo for graphql-server, because those packages are really closely related. For Apollo Client we could consider it as well, but I think overall it's nicer if they're not all in the same repo, because different people work on the different repos. Another benefit of not lumping together is that anyone in the community can start another view layer integration and have it be on essentially equal footing.

We also want to clearly show that Apollo Client isn't a monolithic project, and I think having separate repos makes that really clear.

When it comes to filing bugs, I don't think it matters much which repo they are filed on. Just pick the one you think fits best, and then contributors or maintainers will figure out where the issue really belongs.

**Comment by wizardzloy** [comment]
@helfer It is also hard to search for issues,  but I got your point
