### ISSUE TITLE
apollo-client Node type definitions

### ISSUE THREAD

**Issue by jamir0** [apollostack/apollo-client#1157]
In project used typescript@2.1.4, react@15.4.2, redux@3.6.0, graphql.
i try to use apollo-client and after compiling project received error:
```
[at-loader] node_modules\@types\node\index.d.ts:73:13 
    Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'NodeRequire'. 

[at-loader] node_modules\@types\node\index.d.ts:85:13 
    Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'any', but here has type 'NodeModule'. 
```

packages.json
```
...
"devDependencies": {
   "@types/node": "^6.0.59",
   "@types/webpack": "^2.1.0",
    ...
    "apollo-client": "^0.7.1",
    "react-apollo": "^0.8.1",
   ...
}
```
Everything was OK, while i have started to use  apollo-client. Does anybody knows how to fix it?

**Comment by helfer** [comment]
@jamir0 most likely you have other typings in your project which define `require`. Apollo Client has node typings which define require, but in your case they do not seem to be compatible with the typings you installed. You should figure out which one that is, and then install the typings that work with your project and apollo-client (that's why we put them in dev-dependencies).

**Comment by jamir0** [comment]
resolved.
i had declarations.d.ts where were declared 
```
declare var module: any;
declare var require: any;
```
i removed such declarations and everything start to be ok.
