### ISSUE TITLE
Docs/Concept: Handling basic form errors using "errors" or alternative concept?

### ISSUE THREAD

**Issue by swernerx** [apollostack/apollo-client#1160]
Coming from REST like a lot of other people I wonder how to differentiate between actual system errors and more trivial form errors. 

I know that I can throw exceptions which are transformed into ApolloError instances. This feels like a typical 5xx error in HTTP. In our case, for form field errors and/or general system warnings (think more of 4xx errors in HTTP) it would be interesting to have a list of invalid forms with error codes attached to all of them.

There is also the idea of normalization of values e.g. auto correct slightly wrong written street names, mismatching zip codes, etc.

For mutations we receive basically a data structure with `data` and `errors`. `data` returns us the data which is defined in the query part of the mutation where `errors` most of the time is relevant for real "hardcore" errors where the system fails to fulfill the request.

Together with my team we figured it would be sensible to add another top-level key on the server side. After some discussion we came with the following data structure:

```
- data
- errors
- request
  - input
    - name: { valid: true, normalized: "Henry Barmer" }
    - address
      - zipCode: { valid: false, normalized: "", errors: [{ code: 456, message: "This zip code does not exist" }] }
      - city: { valid: true, normalized: "" }
  - errors
    - { code: 123, message: "Form validation failed" }
    - ...
```

Our thinking: 

- We want to handle multiple field errors at once and inform the user about all errors.
- We want an easy way to differentiate between system errors (status codes 5xx) and input errors (status codes 4xx)
- We need a mapping of errors to form field ids (mutation variables) so that we can show the errors on their respective fields.

Our questions?

1. Is this something which somehow conflicts with the normal approaches to use Apollo/GraphQL?
2. How do you differentiate between the different levels of errors.
3. Is there some equivalent of status code for GraphQL?

(We are using apollo-react, apollo-client, express-apollo)

**Comment by Poincare** [comment]
Fundamentally, GraphQL doesn't force you to use any particular kind of error handling system. You can create classes based on `Error` in order to create a structure similar to HTTP if you would like.

For your first point, what currently prevents you from presenting/handling all input errors at once? Is it that these errors are presented as responses to different queries, making it difficult to handle them in one block of code?

It seems that you can achieve your second point (i.e. differentiation between system errors and input errors) by subclassing `ApolloError` and creating an error type tree of your choosing rooted at that point. 

For the third, I think this is possible pretty easily since [this PR](https://github.com/graphql/graphql-js/commit/6223245d14f37b472825bc6136798052ea23077f) to graphql-js. I'm not sure if it is being worked on currently.

Please let me know if I have misunderstood any of your points.

**Comment by armstrjare** [comment]
I kind of think this is a concern at the application level rather than the library level.

The way we've been approaching it is to have the "status" of a mutation in the result type. 
```graphql
type SaveProjectResultType {
  success: Bool!
  validationErrors: [String!]
  newProject: ProjectType
}
```

Then your code for handling of the mutation result needs to check whether it was successful, and apply if not, display the validation errors.

**Comment by calebmer** [comment]
@Poincare and @armstrjare make good suggestions. I’m also an advocate of just replicating some validation logic client side. It may be easier to implement and could provide a better user experience at a low cost. I’m going to close this for now. If you feel like you need more help on this I encourage you to open a question on Stack Overflow under the GraphQL tag as this is more of a general GraphQL design question 👍
