### ISSUE TITLE
0.7.1 refetchQueries not working

### ISSUE THREAD

**Issue by DimitryDushkin** [apollostack/apollo-client#1167]
Quite similar to https://github.com/apollostack/apollo-client/issues/1129 besides for `0.7.1`.

**Comment by helfer** [comment]
@DimitryDushkin Thanks! I think this is the same issue as #1129, because we didn't change anything since. Queries that aren't active won't be refetched.

We're working on a solution that makes it possible again to update the cache for old queries without keeping them around forever. Should be a few more days until it's implemented and released.

**Comment by DimitryDushkin** [comment]
@helfer sorry for clear duplicate.
