### ISSUE TITLE
QueryManager gets into a broken state w/ unhelpful error if server returns `errors: null`

### ISSUE THREAD

**Issue by tmeasday** [apollostack/apollo-client#1185]
If your server returns (an incorrect) response w/ `errors: null` (you can achieve this by setting `formatError: () => null` in `graphql-tools`)., then the following error is thrown:

```js
store.js:14 TypeError: Cannot read property 'message' of null
    at http://localhost:3003/static/js/bundle.js:43299:57
    at Array.forEach (native)
    at generateErrorMessage (http://localhost:3003/static/js/bundle.js:43298:28)
    at new ApolloError (http://localhost:3003/static/js/bundle.js:43317:30)
    at http://localhost:3003/static/js/bundle.js:43477:40
    at http://localhost:3003/static/js/bundle.js:43965:26
    at Array.forEach (native)
    at http://localhost:3003/static/js/bundle.js:43962:28
    at http://localhost:3003/static/js/bundle.js:34662:12
    at baseForOwn (http://localhost:3003/static/js/bundle.js:34608:21)
```

Moreever the same error is continually thrown every time any action is dispatched to the store in future (for instance if you call `client.mutate`).

**Comment by tmeasday** [comment]
(I'll try and put a failing test together)

**Comment by calebmer** [comment]
There’s a fix in https://github.com/apollostack/apollo-client/pull/1208 👍

The expected behavior you had in https://github.com/apollostack/apollo-client/issues/1197 is actually kind of hard to implement given that there can be more than one GraphQL error. If we had three errors and one of them was null, would we want to make the one `ApolloError` null? Instead, https://github.com/apollostack/apollo-client/pull/1208 just uses a default message when the error is null.
