### ISSUE TITLE
Changing observable response structure

### ISSUE THREAD

**Issue by Urigo** [apollostack/apollo-client#139]
Right now from the Observable we return the data in the following format:
`data.queryName`

that makes the need of another pipe in Angular 2.0 on top of the default `async` pipe that handles observables.

As we are always returning one query, maybe it's a good idea to return the observable without those prefixes.
The question is how to handle errors.
I think that we should use the stadard way with supplying an `error` function hanlder, as specified here:
https://github.com/zenparsing/es-observable
and here: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html

@martijnwalraven @stubailo

**Comment by martijnwalraven** [comment]
We already use the `error` handler for true errors like network errors, but the question is what to do with graphql errors.

The issue is that a graphql response can include both partial results and a list of errors. So we would have to either not support partial results or include some other way of getting access to the errors.

**Comment by stubailo** [comment]
I think this is just inherent to GraphQL, plus what would you do if you had two root queries, which is totally possible? I guess we could say you should make two observables.

**Comment by stubailo** [comment]
To put a point on it, I am pretty confident that the thing the observable returns should be identical to the response sent from the GraphQL server, which is an object with `data` and `errors`.
