### ISSUE TITLE
Make it possible to use an existing observable implementation

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#149]
For example, to easily integrate with RxJS.

**Comment by haf** [comment]
Could you guys please document your issues and pull requests with an actual description that describes what is wanted and/or what is being merged? I would prefer not to have to hunt through the code-base and the diffs just to understand the jest of a PR. E.g. this one — it references #196, but neither actually says what it's about.

I'm interested in this, since I consider redux a great pattern for applications, I've worked extensively with redux-observables and rxjs and: reading the source code of this repository gave me a real scare — how is this code-base maintainable? As such, I'd like to understand what is going into the library — especially when it comes to clearly thought through concepts like observables (as opposed to less well thought through pieces of code, like the [`QueryManager`](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts) component in this repo)
