### ISSUE TITLE
Mutation Creators

### ISSUE THREAD

**Issue by abhiaiyer91** [apollostack/apollo-client#160]
This issue is to assign work surrounding the concept of  `Mutation Creators`.

### What are Mutation Creators?

Much like Action creators are functions that create actions, `Mutation Creators` are functions that create Mutations. 

### What needs to be done?

- [ ] Need to figure out a clean way to recommend a pattern for using `Mutation Creators`.
- [ ] Need to update example repos with this pattern
- [ ] Need to update docs with recommendation

**Comment by abhiaiyer91** [comment]
These are my thoughts:

https://gist.github.com/abhiaiyer91/6c39108c1908261a708470710977d16a

**Comment by jbaxleyiii** [comment]
A few thoughts:

Performing validations in a component will certainly be a pattern (similar to allow and deny rules in some cases). I think a consistent way to do this is possible (and wanted), but probably wouldn't be part of the client itself.

The issue of needing to refetch (https://gist.github.com/abhiaiyer91/6c39108c1908261a708470710977d16a#file-dispatchmutation-js-L36-L38) should be solved in most cases by https://github.com/apollostack/apollo-client/issues/144 but in the meantime having an easy way to do it is nice.

I'd rather return the promise directly instead of the callback.

From the gist, I gather the issues with the current implementation of `mutations` are:
- [ ] how do I do validation
- [ ] how do I trigger a watchQuery `next()` after the mutation

If those are the only issues, it may be worth discussing adding `validate: (variables) => boolean` on the mutation object? Since `mutate()` can be called as a function that passes its own args, you could certainly do it in the mutation function you define but it could be helpful / a clearer separation of concerns if done in its own method.

Aside from that we need to address #144 for sure

**Comment by abhiaiyer91** [comment]
Yes exactly @jbaxleyiii 

I think it would be valuable to give that utility for validation. I think most people will implement their same validations over and over again.

**Comment by jbaxleyiii** [comment]
@abhiaiyer91 if you good with it, I'll open an issue around validation and close this one out?

**Comment by abhiaiyer91** [comment]
Let's do it
