### ISSUE TITLE
Move refetch(), startPolling() and stopPolling() from Subscription to ObservableQuery

### ISSUE THREAD

**Issue by martijnwalraven** [apollostack/apollo-client#194]
Interoperability with other Observable implementations (see #149) means we have no control over the Subscription object users end up with.

For example, `Rx.Observable.from(handle).subscribe()` would return an RxJS Subscription object without the Apollo-specific helper methods.

So I think it makes most sense to move these methods to `ObservableQuery` (maybe this needs a better name, like `QueryHandle` or simply `Query`). 

This will require some refactoring of the current code to share fetching and polling logic between observers, but that actually seems like a better design anyway.

```
const handle = queryManager.watchQuery({ query });
handle.refetch();
handle.startPolling();
handle.stopPolling();
```

**Comment by jbaxleyiii** [comment]
@martijnwalraven I'm all for it!

**Comment by stubailo** [comment]
@Urigo, @kamilkisiela I think we should fix this ASAP. I was just talking to @purban and it's a bit weird because people from Angular 2 are going to be expecting RxJS, not a regular old observable. With this merged, at least we can implement a feature to replace the observable shim with Rx.

**Comment by kamilkisiela** [comment]
Maybe you guys will be interested in it.

Here's [an implementation](https://github.com/apollostack/angular2-apollo/blob/d38cbcd28323ff56457acc5281b0775c7e3a41b3/src/apolloQueryObservable.ts) of `QueryObservable` that works with RxJS.

---

```ts
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/from';

const origin = client.watchQuery(options); // QueryObservable
const obs = Observable.from(origin);

origin.refetch(); // works
obs.refetch(); // refetch is undefined
obs.ish.refetch(); // works (it should) because `ish` is a reference to `origin`
```

To solve that problem I created custom observable called `ApolloQueryObservable` that extends `Observable` from RxJS. `QueryObservable` is being hold under `apollo` property. This way I could create methods like `refetch()`, `startPolling()`, `stopPolling()`.

---

```ts
import 'rxjs';
import { ApolloQueryObservable } from 'angular2-apollo';

const origin = client.watchQuery(options); // QueryObservable
const obs = new ApolloQueryObservable(origin);

origin.refetch(); // works
obs.refetch(); // works

obs.map(customMapFunction).refetch() // refetch is undefined
```

As you can see, it still won't work with operators. Here's why.

Every operator uses [`Observable.lift()`](https://github.com/ReactiveX/rxjs/blob/master/src/Observable.ts#L60-L72) method, for example [`map()`](https://github.com/ReactiveX/rxjs/blob/master/src/operator/map.ts#L42).

`Observable.lift()` creates new `Observable`, then assigns the current observable under `source` property. Here the moment where our custom methods (refetch etc) are being dropped.


I solved this by [overwriting `lift()` method](https://github.com/apollostack/angular2-apollo/blob/d38cbcd28323ff56457acc5281b0775c7e3a41b3/src/apolloQueryObservable.ts#L22-L29).

---

@stubailo @martijnwalraven @jbaxleyiii @Urigo I was thinking about moving this `ApolloQueryObservable` (in different name, whatever) to `ApolloClient`, because it's not angular2 specific and will help a lot of people, I think.

**Comment by stubailo** [comment]
Hmm, sounds like this could be a good idea. Could you open a new issue with some details about how `ApolloQueryObservable` works?

**Comment by kamilkisiela** [comment]
#430
