### ISSUE TITLE
Create option to force queries to use local store

### ISSUE THREAD

**Issue by siegesmund** [apollostack/apollo-client#225]
There are instances where it's advantageous to prevent a query from trying to fetch data from the server. For example, if two components depend on the same data, and are both connected to the same query, both queries will fetch data from the server if neither query has completed before the other is executed. In instances like these, finer grained control would be useful.

In reference to: https://forums.meteor.com/t/apollo-query-patterns-with-react-redux/23347/5

**Comment by abhiaiyer91** [comment]
@stubailo If we have already fetched data via a query, should this `data` be able to be connected in non-apollo containers via `mapStateToProps`?

**Comment by stubailo** [comment]
I think this can be a pretty small feature:

(1) A new option to `query` and `watchQuery`, maybe called something like `noFetch`, which tells Apollo to not do any fetches at all for this query, and simply return what it can find in the store at the time.

This will enable people using Apollo `connect` to use data from the store in `mapQueriesToProps` without actually fetching anything.

@abhiaiyer91 it seems what you're talking about is a bit different, and I'd say it warrants a separate issue, which is the ability to load Apollo data from the Redux store directly without going through ApolloClient? I guess I'm not really sure why people would need to do that, since eventually the Apollo `connect` will be much more optimized than custom loading in the regular Redux `connect`. At the very least you'll need to use `reselect` in very clever ways to avoid re-renders.

**Comment by stubailo** [comment]
> I guess I'm not really sure why people would need to do that, since eventually the Apollo connect will be much more optimized than custom loading in the regular Redux connect. 

Just found a reason - other redux wrappers like Redux Form.

**Comment by siegesmund** [comment]
Yea, I'm glad you did ;). I've been looking for a better answer than 'because it feels right to me.'

To me, it seems natural that we should be able to blend apollo seamlessly into Redux. One of the major design points of Redux is the single state container. With Apollo/Redux we now have a nested state container within a container, that can no longer be easily directly accessed. The Apollo object is now available sort of globally via redux, and we can use it to inject data into our components, but we are forced to trade the control, precision and power of redux for the intelligence and brevity of code of Apollo.

Right now, I am using Apollo client in two ways: 1) I am using Apollo client and writing all of the redux types, actions, reducer etc. In other, words, I'm not using the Redux integration. 2) For some components, I'm trying to use the Apollo/Redux integration. Being able to access Apollo data in the store would largely remove this distinction.

**Comment by stubailo** [comment]
Filed a new issue here: https://github.com/apollostack/apollo-client/issues/227
