### ISSUE TITLE
Request: Simplify apollo-client middleware

### ISSUE THREAD

**Issue by ciwolsey** [apollostack/apollo-client#253]
Right now we have to do something like this:

``` javascript
networkInterface.use([{
  applyMiddleware(request, next) {
    if (!request.options.headers) {
      request.options.headers = new Headers();
    }
    request.options.headers.Authorization = token;
    next();
  }
}]);
```

It would be much nicer to be able to provide regular functions to networkInterface.use rather than having to use applyMIddleware. Thoughts?

**Comment by czbaker** [comment]
I definitely agree.   Upon us figuring out how this works today, I feel like you should just be able to provide functions instead of using `applyMiddleware`, unless there's a specific reason for this design choice.

**Comment by zimme** [comment]
In the Express world it's like this:
```js
var app = express();

app.use(function (req, res, next) {
  console.log('Time:', Date.now());
  next();
});
```
it works the same with router level and error middleware, except the arguments might be different.

So it makes sense to have it access straight functions as that what people are used to, coming from other worlds.

**Comment by czbaker** [comment]
@zimme:  Exactly.  When I was trying to figure out middleware, since I needed it for authorization in my current project, I looked to the Express middleware docs for help, as it was undocumented here.

I was super confused when I realized that it wasn't the same, and that there was an `applyMiddleware` requirement that I was unaware of.

**Comment by bryanchriswhite** [comment]
Is this issue something that people want to be fixed?

I just opened #547, which affects the same part of the code and would be convenient to fix at the same time (assuming my expectations on how to resolve this issue are correct).

I am also curious if there is any explanation to why middleware is required to be an object with an `applyMiddleware` property because, based on the code, it seems arbitrary.

**Comment by stubailo** [comment]
If someone wants to come around and work on this that's great, but it's not a high priority right now, since people seem to be able to figure it out via the examples.

**Comment by helfer** [comment]
cc @DxCx @calebmer if we overhaul the network interface, we should keep this in mind. I'm closing it now since it's an ancient issue.
