### ISSUE TITLE
How to initialize apollo client with just the return of query

### ISSUE THREAD

**Issue by antitoxic** [apollostack/apollo-client#258]
I have a graphql server and it's neither apollo server or node. It's python's graphene server. I will user React and server-side rendering via a separate node process which I will pass an object which matches the data for a graphql query. Most backends that are not javascript are using the same flow.

[In the docs](http://docs.apollostack.com/apollo-client/index.html#store-rehydration) it says that server-rendering is possible if the precalculated state from the store is supplied to apollo like `new ApolloClient({  initialState: apolloStateTree)` And apollo's state-tree looks like this:

```
{
  "queries": {},
  "mutations": {},
  "data": {
    "ROOT_QUERY.allFilms": {
      "totalCount": 6
    },
    "ROOT_QUERY": {
      "allFilms": "ROOT_QUERY.allFilms"
    }
  }
}
```

Is it possible (and how) to initialise apollo by just providing the query and its matching data:

```
{
  "query": "{ all: allFilms { totalCount } }",
  "data": {
    "all": {
      "totalCount": 6
    }
  }
}
```

?

**Comment by Poincare** [comment]
This doesn't seem to possible at the moment but once we factor out the cache normalization/denormalization code (see #255), this should be easy to implement.

**Comment by antitoxic** [comment]
Yep, the same was discussed in slack. Copying from there:

>  I think right now I will have to do an ugly workaround - pass the query data from the server to client, then on the frontend I will have 2 apollo clients, one real and one that uses a  mock NetworkInterface that simply returns the server query data. I will then use the state from the mock apollo client and pass it as initialState to the real apollo client.

**Comment by helfer** [comment]
@antitoxic are you still interested in this, or is the SSR support in react-apollo good enough now?

**Comment by antitoxic** [comment]
@helfer I haven't checked react-apollo yet. Is it a problem to come back with a comment in 2 weeks?

**Comment by helfer** [comment]
Sure, no problem. Do you mind if I close the issue in the meantime?

**Comment by helfer** [comment]
We're going to add an interface that allows you to easily read denormalized data from the store and write denormalized data to the store independent from actually running GraphQL queries, so this should become very easy soon. I'm closing the issue now because, well, it's been four months.

**Comment by yash0087** [comment]
I am very much interested to know when this will be available. I have couple of scenarios where I would like to use setting/getting data directly from "apollo" part of redux store.
1. I have multiple container level components which connects to redux store. Since I cant access the "apollo" specific data directly, i have to use "qraphql(query)" to get the data from the store and pass it as props into my component.

2. If I use the "props" option for "qraphql" config, when the react renders the first time the props throws error when it tries to match data from a nested object since it doesnt exist in the "apollo" part of the store.

Example,

```
qraphql(query , {
    props: ({data}) => {
        sampleProps: data.a.b.c
    }
})
```

If i had the option to set the denormalized data into "apollo" store on the app startup, i can populate the store with default data and then i dont have to worry about my data being null|undefined anywhere in my code!

Or do you have any alternative suggestions for the above two problem i have?

**Comment by 1player** [comment]
Sorry to comment on a closed topic, but is there any news or tracking issue?

**Comment by reverie** [comment]
@helfer Is there another issue where we can track that feature?

**Comment by helfer** [comment]
@reverie You should be able to do this now by simply running `client.writeQuery({ query, data })`. Obviously you'll need the query, the data and the variables (if you used any).

**Comment by stubailo** [comment]
Here are the docs! http://dev.apollodata.com/core/read-and-write.html#writequery-and-writefragment
