### ISSUE TITLE
Optimistic updates

### ISSUE THREAD

**Issue by spicydonuts** [apollostack/apollo-client#287]
Client-side optimistic updates should work pretty seamlessly if there's a way to tell the mutation "here's the data to use until the response comes back".  The trick will be figuring out how to get that into the current syntax and deciding how it gets undone in the event of a failure, since a failed server call probably can't be expected to reliably undo the optimistic update by sending down the opposite change (seeing how it failed, after all).

**Comment by stubailo** [comment]
I think we can use one of the two, since the store is already implemented with Redux:

- https://github.com/ForbesLindesay/redux-optimist
- https://github.com/mattkrick/redux-optimistic-ui

This would mean modifying how we handle the `MUTATION_RESULT` action, and adding an optimistic version that we roll back when the actual result comes back.

Do you have experience working with Redux? Perhaps you could help implement this!
