### ISSUE TITLE
Figure out a strategy for `forceFetch` / polling and SSR

### ISSUE THREAD

**Issue by tmeasday** [apollostack/apollo-client#298]
In getting a POC of SSR in githunt working w/ saturn
 - with this: https://github.com/apollostack/saturn/commit/4a5cbee88b9f77610a36516ca1a735347905c39c
 - particularly: https://github.com/apollostack/saturn/blob/4a5cbee88b9f77610a36516ca1a735347905c39c/server/app.js#L100-L120
 - and https://github.com/apollostack/githunt/tree/saturn-ssr,

I ran into an issue with the use of `forceFetch` here: https://github.com/apollostack/GitHunt/blob/master/ui/Feed.js#L154

We are following @stubailo's simple strategy of rendering once to string on the server to kick off queries and then, once the queries are done, to render a second time and return it to the requester.

Force fetch isn't appropriate at two points of this process:
 1. In the second server render, we don't want to kick off any more queries and we definitely don't want to wait for them. **We basically don't want `forceFetch` at all on the server.**

 2. On the *very first* client render, just after we've rehydrated data, we don't want to force fetch, else the UI will change from "showing all data" to "loading" again unnecessarily. Potentially we *could* do the fetch but not show the loading UI while it's going on, in which case this would perhaps be a `react-apollo` issue cc @jbaxleyiii.

I suspect the (1) could be solved by adding a `neverForceFetch` API to `ApolloClient` and calling it from a server file when setting up SSR. I'm not sure what the best strategy to solve (2) is?

**Comment by Poincare** [comment]
How do you determine when to "end" the first render and stop it from firing any further queries? Once all the components have been rendered and the queries returned?

**Comment by tmeasday** [comment]
Basically just watch the Apollo Client store and wait for all queries to become ready, after doing the first render.

We may run into problems with polling queries also; we should probably consider that as well.

We shouldn't run into any issues with the client re-rendering due to the changes @jbaxleyiii is making [here](https://github.com/apollostack/react-apollo/pull/75), although it would seriously cool to figure out a better solution that just waits for the UI to "queisce" following a strategy similar to @bruno12mota's comment [here](https://github.com/facebook/react/issues/1739#issuecomment-223825012)

**Comment by Poincare** [comment]
Polling queries were what I was concerned about. However, since a polling query should fire one time immediately after it starts (i.e. it doesn't wait around for a polling cycle to send out the query), I think it should have resulted in initial data by the end of the first render.

**Comment by bruno12mota** [comment]
Hey guys! As I've told to @stubailo here https://github.com/relax/relax/issues/228#issuecomment-227503506 I ended up not using a React render for the first render, instead made my own render function on Relate, which doesn't make any markup or virtual tree, it just goes through the components tree, passing props and context as it would in a normal React render making it much more efficient.

In this render I can get the data dependencies, it's a matter of fetching them and put the result in the store. In my case, each data connector has an ID which I believe in your case doesn't happen as you guys have a caching system. So, I think in apollo's case it's a matter of overriding forceFetching and also the polling on the phases of the server side rendering as well as the initial render on the client side (since even if it has a forceFetch it shouldn't fetch the data again).

If you want you can also re-use the render code I made for Relate https://github.com/relax/relate/blob/master/lib/server/get-data-dependencies.js

Just my two cents here 😄

**Comment by tmeasday** [comment]
Thanks for weighing in @bruno12mota, I have followed the thread over there, I was about to post now I've actually pushed my [hacky-POC code](https://github.com/apollostack/saturn/blob/4a5cbee88b9f77610a36516ca1a735347905c39c/server/app.js#L100-L120).

I think your strategy sounds interesting as an optimization. At this point I think just getting it working using React's `renderToString` makes sense to work out the kinks and then we can circle back to improve performance afterwards. Also, it might be interesting to look at a typical app's rendering cost for the "loading" state (which is what you'd render on the first pass), or even short-circuiting rendering data-dependent components (as @sashko is hinting at [here](https://github.com/relax/relax/issues/228#issuecomment-227562769))

I still like the idea of rendering to virtual DOM, waiting, then serializing the virtual DOM to a string, btw.

**Comment by bruno12mota** [comment]
@tmeasday rendering to virtual DOM then setting updates and getting the dom string representation on demand would be ideal yes, that way a lot of the components tree could be reused, but don't see that happening from the React team, at least in the following months (SSR is definitely something that doesn't concern them since they don't need it) 😛 

Performance is an issue with React server side render function. I've actually made a benchmark to test it out https://github.com/relax/relax/issues/247#issuecomment-225205863, the custom render on Relate to get the data dependencies had some good results in comparison (4-5 times faster)

There are more optimizations I have in mind that could be useful for you guys as well, such as caching resolved data dependencies, and caching at a component level. There's actually a really good talk about the later https://www.youtube.com/watch?v=PnpfGy7q96U

**Comment by stubailo** [comment]
I think (1) is correct - we just never want to forceFetch or poll on the server at all. Adding an API to the client to turn that off seems like a fine solution to me.

For (2), I think we could do something really basic, like add a timeout - after instantiating the apollo client, the first 500ms we don't honor the `forceFetch` option.

**Comment by tmeasday** [comment]
Ok, what would be your preferred API for the above, if I send a PR?

**Comment by stubailo** [comment]
I'd say `disableForceFetch: true` and `ssrForceFetchDelay: <ms>` are fine options for the apollo client constructor.

**Comment by tmeasday** [comment]
Sent a PR, let me know your thoughts

**Comment by tmeasday** [comment]
I think we can close this? There may still be issues around polling, but let's solve them when we get to them?
