### ISSUE TITLE
How to load appollo-client with system.js

### ISSUE THREAD

**Issue by manuelfink** [apollostack/apollo-client#318]
I just added angular2-apollo to an angular2 project bootstraped with angular-cli.

Angular 2 is loading modules with systemjs. However it's pain with apollo-client: You have to add every individual lodash function as a module to systemjs to be loaded. Moreover this ends in many requests to the server and inconvenient imports.

Thus I do have the following questions / ideas:

1. Isn't it possible to load apollo-client as a node_module with and also load its sub-depenencies automatically without adding every single to system js? Also asked this at the [angular-cli repository](https://github.com/angular/angular-cli/issues/1222) and [stackoverflow](http://stackoverflow.com/questions/38056983/angular-2-how-to-load-3rd-party-vendor-node-modules-with-sub-dependencies-angula) 
2. Does it make sense to load lodash at once and not every individually needed function separately?
3. Does it make sense to make one single loadable apollo-client file wich includes sub-dependencies?

However I'm not jet that much into SystemJS and module loading (I appreciate) to tell if my thoughts make sense?

**Comment by stubailo** [comment]
Honestly, this seems like a problem with systemjs rather than with Apollo Client. It shouldn't be up to the module author to pre-package dependencies, that sounds like the build system's job. Otherwise the whole concept of dependencies doesn't really make sense.

> Does it make sense to load lodash at once and not every individually needed function separately?

No, because many apps don't use lodash. In this case we would be loading all of lodash just to use a few functions. With Webpack/Browserify/Meteor this is completely transparent to the app developer.

> Does it make sense to make one single loadable apollo-client file wich includes sub-dependencies?

We could do this pretty easily if it makes systemjs easier. How do people usually bundle packages for system? Is there an example I can look at?

@Urigo @kamilkisiela did you run into this problem with Angular?

**Comment by kamilkisiela** [comment]
I have no experience in working with SystemJS. There is [an issue](https://github.com/apollostack/angular2-apollo/issues/23) on `angular2-apollo` on that topic too.

In some way you have to specify which modules you want to load and where the build system can find them. I didn't come up with any rational solution.

Here's an example of SystemJS in use. https://github.com/angular/quickstart

**Comment by Urigo** [comment]
I've just answered it on Stack Overflow here: http://stackoverflow.com/a/38317093/1426570

It's been hard to solve and I totally agree with @stubailo that this is a System.js/Angular CLI issue.

In the answer I link to the solution but also to an active issue about this on Angular CLI.

I think we can close this now
