### ISSUE TITLE
Mutation retry/persistence 

### ISSUE THREAD

**Issue by igrayson** [apollostack/apollo-client#439]
Hi team,

We've been following along with the progress on optimistic updates for mutations, and are considering how best to augment one remaining feature to bring this client to parity with our existing (non-GraphQL-based) redux architecture: request retries which persist through application restarts.

I'd be grateful for feedback on the follies or values of the following actions, to get us there:
- Use the new `optimisticResponse` parameter (and associated logic) for its intended purpose (https://github.com/apollostack/apollo-client/pull/336).
- Build a middleware for our `NetworkInterface` which retries mutation requests, effectively keeping a mutation request "in flight" longer -- as far as optimistic update logic is concerned -- while the application is running.
- To achieve persistence of pending requests across app restarts, build a reducer which listens to `APOLLO_MUTATION_*` actions and maintains sufficient data to redrive (in the form of fresh `client.mutate()` calls) in-flight requests when the app boots up. From inspecting live actions, it looks like the `APOLLO_MUTATION_INIT` action has enough to rebuild the mutation document, fragments, variables, etc., for a fresh `mutate()` call.
- Persist our redux store, keeping the keys for this pending request-tracking, and optionally `apollo.data` (but omitting other `apollo.*` keys). We're using `redux-persist` to achieve this today for other redux state -- which in turn uses `AsyncStorage`.

**Comment by stubailo** [comment]
Hey I'll think about this in more detail later, but I'm curious - have you already implemented all of the bullet points above, or is that something you are thinking about doing?

**Comment by igrayson** [comment]
We haven't implemented this. We're looking this for the near future.

**Comment by Poincare** [comment]
@igrayson 

Currently, your queries created through `watchQuery` will be refetched automatically on an "application restart" if you use `resetStore`. I'm not sure if doing this sort of thing would make sense for mutations since they generally modify server state and you definitely wouldn't want to retry all mutations. Does it make sense to just expose a `refetch` method on a mutation promise?

**Comment by helfer** [comment]
I think it should be possible to get 90% of the way there just by implementing a custom network interface that retries mutations. I'll close this for now, but I'd be happy to keep the discussion going.

**Comment by manuelfink** [comment]
Just had the same thoughts having problems with network latency and availability on mobile devices with queries. Thus not sure if this is a good fit here or better be off in a new issue. @helfer, whats your opinion?

I think retrying is a pretty **default use case** in modern web application architecture to have/rely on retries. Once in a while a **request gets lost or a server goes down in an scalable architecture**

**Retry Query:**  I think it would be really handy to have a retry option per query. The client retries until it gets an expected response this may be either a successful mutation or an rejection of undenied. For long running request or lost request it makes a lot of sense to automatically retry since they most likely got lost. Eg my idea is if the response is not here within timeout resend it a second time. The first response coming back fulfilling the request fills the apollo store. No more reties happen after this.

**Retry Mutation:** In a world of optimistic updates the server can be able to sort out multiple updates. I think retrying may not make sense for every mutation though eg. if you have a classical relational database thus it must be a tunable option and may hardly rely on the type of mutation.

**Persistance:** Interesting idea. Definitely not a default use case in my opinion. However I think this is REALLY interesting enhancement in combination with service workers. Just a tumb idea: If this logic is wrapped in a web/service worker or a background service eg in cordova mobile apps persistance makes a lot of sense and this becomes a really interesting feature making it partly competitive alternative to firebase. What I love about firebase is the rock solid sync, without having to worry about connection and request handling. Just say I like the following data to be in sync. Retrying may not be the same but be an suitable alternative.

**Comment by calebmer** [comment]
Retry logic should really be in the network glue code, and not on a per-query basis. We may be willing to merge a PR that implements retries in the network interface for queries, but not mutations as that gets problematic as you mention.

**Comment by igrayson** [comment]
We implemented the bullets in my original post (about 6 months ago), and are happy with the result.

**Comment by helfer** [comment]
@igrayson That's cool! Would you be willing to share your implementation / insights?

**Comment by kuka** [comment]
@igrayson Is there a chance you could share the implementation?

**Comment by psamim** [comment]
@igrayson It would be great if you could share some implementation.

**Comment by ArtisanalPickle** [comment]
@igrayson +1 on that implementation :)

**Comment by miguelocarvajal** [comment]
@igrayson +1 if you could share some implementation code
