### ISSUE TITLE
Compile list of changes before alpha release

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#45]
@jbaxleyiii alluded to this in a comment earlier. If we want people to start testing this on basic queries and stuff, we should put out an alpha release where there is a clearly documented set of supported features. We should start writing down which features that should include, and see if that represents a coherent story. (For example, a drop-in replacement for Lokka presents a pretty good story, especially if there are a few crucial features in addition)

**Comment by stubailo** [comment]
This will also let us iron out a release process, and make sure the package is indeed installable. I'd also suggest this includes removing the dependency on _all of LoDash_...

Should be pretty easy to create a custom build of lodash that just has the functions we use in production, or we can use the single-function packages.

**Comment by jbaxleyiii** [comment]
@stubailo that sounds fantastic. I'd like to setup the docs using gitbook so we get something akin to http://redux.js.org/ for now.

I prefer doing single-function packages because its paints a clear usage picture and is easier to add / replace. I would also like to remove the deps on fetch and promise and let the environment handle supporting of that. With relevant documentation and perhaps a versioned build of apollo with polyfills included.

**Comment by stubailo** [comment]
Sounds great to me!

**Comment by stubailo** [comment]
I made a milestone `alpha`:

- [On GitHub](https://github.com/apollostack/apollo-client/issues?q=is%3Aopen+is%3Aissue+milestone%3Aalpha)
- [On Zube.io](https://zube.io/boards/52630616?milestone=1669649)

No need to have an issue here I think.
