### ISSUE TITLE
Figure out how much bundle size would increase if we updated all of the lodash packages

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#491]
See the list here: https://github.com/apollostack/apollo-client/pulls?q=is%3Apr+author%3Agreenkeeperio-bot

It's possible they have overlapping dependencies, so it could be pretty small.

**Comment by Poincare** [comment]
For some weird reason, it seems that if I update a few `lodash` packages individually, the bundle size turns out to be larger than if I just run `npm update`. 

Before any updates, the bundle size was 35.32 KB. Here are the bundle sizes after running updating each of these packages (in the given order):

```
lodash.mapvalues: 37.4kb
lodash.has: 38.26kb
lodash.countBy: 39.28kb
```

After running a full `npm update`, the bundle size is `37.79kb`. So, I guess this isn't too much of a concern.

**Comment by stubailo** [comment]
OK, let's go ahead and update all of the deps at once then.

**Comment by Poincare** [comment]
So, the `node_modules` are in gitignore and we've set `package.json` to the lowest acceptable version (as we probably should), so what do we need to update? Just the bundle size?

**Comment by helfer** [comment]
🍂
