### ISSUE TITLE
Efficiently polling for added/changed/removed items in a list

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-client#504]
Hi, I need to display specific data from a table and I want to reactively display when data is added, changed or removed. With Apollo this is possible with polling, yet after coming from Meteor subscription mechanism and OPLoG optimisation I have a mental problem with this approach.

Does Apollo get All data at every poll, or is there any optimisation mechanism in place? I tried only obtaining data which have a newer modification timestamp that a provided threshold, but that's enters page only with new data.

So, my question would be:

1. Is it possible to obtain the data reactively and merged with Apollo store?
2. If not, how can I approach this incremental change  in Apollo store?

Thanks

**Comment by Poincare** [comment]
You can use the `fetchMore` API in order to fetch only the new data and then merge into the store as per your application's needs. 

Polling queries do fetch the entire query again, but if you query for only "new" information, you can simply merge it into the existing data in the store with `fetchMore`.

**Comment by tomitrescak** [comment]
Is this documented at some place so I know how to use it?

**Comment by tomitrescak** [comment]
Also, does it work with Apollo-react? I cannot find it

**Comment by tomitrescak** [comment]
Also, does it work with Apollo-react? I cannot find it

**Comment by tomitrescak** [comment]
@Poincare, I just spent an hour trying to find anything on fetchmore. The only thing available are some pull requests and discussions in unclosed tickets on apollo-client issues. 

I know you are very busy guys and I am really grateful for all the work you do, but closing this ticket by saying .. "use fetchmore" without any other information is not very helpful. On top of that it seems that this functionality is not even tested (https://github.com/apollostack/react-apollo/pull/123) and merged only two days ago.

Questions related to fetchmore:

1. What is the reconciliation strategy on updates?
2. Does it work with react-apollo?
3. Will there be any documentation?

**Comment by stubailo** [comment]
Here's how you use it, perhaps the documentation wasn't there yet when you were asking about it, or you didn't think to look under "pagination": http://docs.apollostack.com/apollo-client/pagination.html#fetch-more-new-query

This isn't as nice to use for polling, because it's designed for imperative stuff like pagination.

Right now, reactivity on added/changed/removed data from lists is where Meteor is _heavily_ optimized - I doubt you'll find a better implementation of that mechanism almost anywhere else. Apollo doesn't claim to be nearly as good at that particular issue.

One thing we're currently working on is realtime subscriptions, which will let you push events to the client when you know something might change the list you are looking at.

**Comment by smolinari** [comment]
> One thing we're currently working on is realtime subscriptions, which will let you push events to the client when you know something might change the list you are looking at.

This would be a great addition!!! Looking forward to it.

Scott

**Comment by helfer** [comment]
Now that we have subscriptions, I think should be pretty easy to do.
