### ISSUE TITLE
Idea: Global fragment map

### ISSUE THREAD

**Issue by nevir** [apollostack/apollo-client#512]
In our app, we have a fair number of commonly used fragments (especially for queries triggered via non-UI code).  It'd be pretty handy to register fragments globally with an apollo-client instance to cut down on verbosity when querying

Maybe as a `fragments` argument when constructing the client?

**Comment by Poincare** [comment]
We thought about this when designing the `createFragment` concept. At the time, we came to the conclusion that handling global state like this might actually be somewhat complicated to reason about and we went with a more local approach.

However, from the discussion in #480, it is evident that we will end up implementing this in some capacity since we want to be able to reference fragments by names only rather than by the references returned by `createFragment`.

**Comment by Poincare** [comment]
I'll go ahead and close this since this suggestion is pretty much a part of #480. We can re-open if this is not the case.
