### ISSUE TITLE
Search? Full-text search?

### ISSUE THREAD

**Issue by dbx834** [apollostack/apollo-client#514]
Hi,

How good is Apollo/ how good can it be for things like searching and full-text search?

Apollo would be the man-in-the middle. Will this pipe - one wraps the search as a query, listens to input 'onChange' event, fires the query, and displays the result - work well?

On the back, the API can talk to anything, be it Elastisearch, or Mongo, or XYZ.

I'm gonna try it out. Any reasons why such a thing should not be built?

Thanks

**Comment by Poincare** [comment]
This should work just fine. In fact, we do implement search within the Meteor Galaxy UI with Apollo Client on the frontend.

**Comment by stubailo** [comment]
Yep, this should work great! Same way you would do search with a REST API.

**Comment by waldothedeveloper** [comment]
@stubailo  or @Poincare  is there any "out of the box" solution for fuzzy search ( or full-text search) solution built for Apollo Client in 2019????
AWS provides AppySync, we have the great Algolia, Azure with their Cognitive Search....so, is there anything like that ( doesn't have to be that powerful though) or any JS alternative that I could implement? 

For example I need to finish a project in two days -literally- and I would like to provide the users to find their company name on a search box instead of scrolling a long list of +152 companies...

I'm using React with Apollo client. Apollo server on the backend asking the info to AutoTask SOAP API. 

Any idea...please let me know! 
Thanks

**Comment by NZaleski** [comment]
@waldothedeveloper did you ever find the fuzzy/full-text search solution with Apollo?
