### ISSUE TITLE
Allow passing in an existing Redux store and pick which key in the store should be managed by Apollo

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#61]

**Comment by jbaxleyiii** [comment]
@stubailo this will require a partial rewrite to move the default store generated from `createApolloStore` to be a combined reducer where all apollo data will live under a specified key. I'm thinking nesting it under an `apollo` key makes the most sense.

In order to support a dynamic key, we will need that to be an input of the `ApolloClient` and passed to query manager (I think, still working through it).

As long as you don't see any troubles with this direction, I'll proceed!

**Comment by stubailo** [comment]
yeah that sounds great! It would be good if it was possible to just not pass in a store, in which case Apollo would make one for you. Basically having flexibility while having sane defaults.

**Comment by jbaxleyiii** [comment]
@stubailo yep! 100% still possible!

**Comment by stubailo** [comment]
Fixed by #81

**Comment by jbaxleyiii** [comment]
@stubailo this closes out our needs to get this into production :tada: :tada: I'll let you know when it's alive and working in our app!

**Comment by stubailo** [comment]
Dude, amazing! Let me know. Excited to see our first set of production bug reports 😄 

Sounds like I should get those breaking API changes in today, so that you don't have to make random weird changes once you start using it: https://github.com/apollostack/apollo-client/issues/82

**Comment by gschmidt** [comment]
@jbaxleyiii Super exciting! It's great having you guys as a partner. I can't wait to hear how it goes.

**Comment by johnthepink** [comment]
@stubailo if you don't get them all in today, I'd be happy to help you finish next week before I start integrating.

**Comment by camiloazula** [comment]
Is this one implemented already?

**Comment by stubailo** [comment]
http://dev.apollodata.com/react/redux.html
