### ISSUE TITLE
Is it possible to access the Apollo Client from a Redux reducer?

### ISSUE THREAD

**Issue by ashah888** [apollostack/apollo-client#691]
Is it possible to access the Apollo Client from another redux reducer somehow?

For example, I'd like to be able to reset the Apollo client/store when an authentication login/logout event happened.

**Comment by stubailo** [comment]
Yeah I think the right thing to do is to import your Apollo Client instance into the reducer module and just call it directly from there.

**Comment by kachkaev** [comment]
@stubailo could you please consider adding an example to the docs? I'm also looking into linking these two data-management tools.

Not that it's too difficult to come up with some solution about Apollo and pure redux, it's just very interesting to know how Apollo guys see this relationship.

**Comment by kachkaev** [comment]
My original idea was to try writing [selectors](https://github.com/reactjs/reselect) that grab some data from the `apollo` substate in the store. This initial thought came to me because I read that Apollo uses redux under the hood. After looking into what's inside the store with the DevTools I changed my mind, but it took some time to figure this out though xD

Someone else might think the same way, which means that you can save a lot of people's time by guiding them a bit :–)

**Comment by stubailo** [comment]
We're about to do a refactor that will make it _much_ easier to use GraphQL queries as selectors, so that you don't have to worry about the store format. Follow along here: #726
