### ISSUE TITLE
0.5 release

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#726]
We're going to do a big refactor of the source code in the next couple of days to change the internals and improve the API. Anyone planning to make a big PR might want to hold off until we're done.

**Comment by stubailo** [comment]
Wow this sounds ominous! But also great since we'll be much better positioned for future improvements.

**Comment by stubailo** [comment]
Things we might want to implement:

- https://github.com/apollostack/apollo-client/issues/706
- https://github.com/apollostack/apollo-client/issues/646
- https://github.com/apollostack/apollo-client/issues/644
- https://github.com/apollostack/apollo-client/issues/615
- https://github.com/apollostack/apollo-client/issues/616
- https://github.com/apollostack/apollo-client/issues/617

Additional stuff:

1. Move to graphql-anywhere
2. Implement stuff from this document: https://meteor.quip.com/hyaMALbIQFK9

**Comment by kachkaev** [comment]
Hi guys,

I know this is a hard question to answer, but what is your rough estimate for this release? I'm not expecting to hear the exact date as I understand that there is still too much uncertainty given the number of open issues. However, what would be good is to know the order of the deadline – is it expected to be in a couple of weeks or sometime next year?

The main reason why I'm curious is because I'd love to try a GraphQL file upload (#586) at some point. You seem like preparing some great changes and I'm really looking forward to play with them!

**Comment by kachkaev** [comment]
Hmm.. I remember seeing #586 in `Release 0.5` milestone, which was added there 8 days ago. But that label is no longer there.

**Comment by stubailo** [comment]
GitHub keeps track of milestones being added or removed, so I don't think it was.

0.5 is currently very close to release, so any new features would be something for the next release.

The first step would be working on a design, perhaps let's talk on the existing issue or open a new issue about file upload to do a discussion?

**Comment by helfer** [comment]
lined up in #843
