### ISSUE TITLE
Can client side store/cache be replaced with different implementation (for example based on Immutable.js, mori)

### ISSUE THREAD

**Issue by userno5718** [apollostack/apollo-client#838]
Currently store/cache is a plain JS object. Is there an option to replace it with immutable/mori hashmap?

There is resultTransformer but converting from JS objects every time seems to be unnecessary overhead.

**Comment by stubailo** [comment]
What's the use case for doing this? It would certainly be possible, but the normalization logic is relatively complex so it would be a lot of maintanance to have several versions of it.

**Comment by userno5718** [comment]
We use mori extensively in our app (not only as client-side store, but in components aswell) and we would like to move to apollo/graphql. It would allow us to leave components untouched.

To make it possible it would be great to have an option to provide custom implementation of store/cache when creating ApolloClient.

I guess having some kind of interface that writes/reads to/from the store that could be swapped out.

**Comment by clayne11** [comment]
Something similar is done in `redux-form`. All of the object mutation methods are abstracted out into helpers and you can initialize the library with either set of helpers. You can see the helper functions here: https://github.com/erikras/redux-form/tree/master/src/structure

**Comment by calebmer** [comment]
We will probably never allow custom store implementations as that would just be way to complex :blush:

However, the more interesting thing here is really transforming the results after we create them for the internal Apollo store. For that we have a [`resultTransformer`](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.constructor) configuration property which you should definitely take a look into. Otherwise this is really a user land concern. We would love to see an `apollo-client-immutable` or an `apollo-client-mori` which provides a nice integration with these libraries. Let us know if you end up building this :+1:
