### ISSUE TITLE
Custom error, "responses.map is not a function"

### ISSUE THREAD

**Issue by richardkall** [apollostack/apollo-client#876]
Hi,

I'm using `graphql-server-express` and my server is set up like this:

```
server.use(
  GRAPHQL_ENDPOINT,
  authenticate,
  bodyParser.json(),
  graphqlExpress((req) => ({
    context: createContext(req),
    formatError,
    schema
  }))
);
```

The `authenticate` middleware throws an error if the JSON web token doesn't validate:

```
import jwt from 'jsonwebtoken';
import {JWT_SECRET} from '../../config/auth';

export default (req, res, next) => {
  if (req.headers && req.headers.authorization) {
    const parts = req.headers.authorization.split(' ');
    const authToken = parts[1];

    try {
      const decodedToken = jwt.verify(authToken, JWT_SECRET);
      req.decodedToken = decodedToken;
    } catch (error) {
      return res.json({
        data: null,
        errors: [{
          message: 'Invalid or expired authentication token.'
        }]
      });
    }
  }

  return next();
};
```

However, when `apollo-client` is trying to parse this on the client, it fails with `Network error: responses.map is not a function`. Is it possible it respond with a GraphQLError outside of the GraphQL server? Or any ideas how I can solve this?

Thanks!

**Comment by helfer** [comment]
are you using transport batching by any chance?

**Comment by richardkall** [comment]
Yes.

**Comment by danimbrogno** [comment]
Had the same problem, switching to normal network interface solved the problem.

**Comment by helfer** [comment]
@richardkall actually, after looking at your code I realized that this is due to an invalid response from your server. The response should be an array of GraphQL results `[{ data: ..., error: ... }, ...]`. Your server just returns a single response, which is not a valid JSON response for a batched request. Your middleware will have to check if the request expects a single response or an array.

I made sure it throws a more useful error message in #893.
