### ISSUE TITLE
Add more functions to the query handle

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#88]
These are the ones I can think of so far:

- [ ] onError
- [ ] isLoading
- [ ] getResult
- [ ] getError

**Comment by martijnwalraven** [comment]
Would it make sense for `getResult` to return a promise? Maybe combine it with `getError`?

Also, I'm not sure what naming conventions people are following in JavaScript nowadays, but maybe we could get rid of the `get` prefix? I see that more and more, like the functions on [Body](https://developer.mozilla.org/en-US/docs/Web/API/Body) as part of the `fetch()` API.

**Comment by stubailo** [comment]
I was thinking getResult would return whatever the result in the store is at this exact moment synchronously- it's the answer to that thing we were talking about with the query callback always being async.

**Comment by stubailo** [comment]
And right now the way we are doing it is using the result callback for GraphQL errors, and a different callback for fatal errors

**Comment by martijnwalraven** [comment]
Thinking about it some more, I'm not sure how useful returning the result synchronously is. I would say you always want the latest result, but if a result is not yet available it makes sense to wait until it is. A promise also has the benefit that it has error semantics built in, so there is no need for a separate `getError`.

```
// GraphQLResult can contain errors
type GraphQLResult = { data: any, errors: Array<GraphQLError> }

// Single result
await client.query(query) // returns Promise<GraphQLResult>, rejects on network error etc.

// Or alternatively support calling result() on a query handle
await handle.result()
```

I also think we need to consider interoperability with Observers, especially because these are used quite heavily in Angular 2. They are used even for single values, where you would expect a Promise, in the [HTTP service](https://angular.io/docs/js/latest/api/http/Http-class.html) for example, because they have the benefit that they can be canceled.

Maybe something like:

```
// Either return Observable from client.watchQuery or allow calling observable() on a query handle
let observable: Observable<GraphQLResult> = client.watchQuery(query);

// Observable supports multiple subscribers

let subscription = observable.subscribe({
  next(result: GraphQLResult) { },
  error(error) { }, // Network error, etc.
  complete() { }
});

subscription.unsubscribe()
```

**Comment by stubailo** [comment]
Yes refetch is a good idea! And I feel like this isn't the right place to worry about specific UI integrations. Angular people will want an angular optimized wrapper anyway so I feel like we shouldn't think about it too hard yet. I bet only alpha-testers and advanced users will end up using the query APIs directly.

**Comment by stubailo** [comment]
Btw sorry my answers are pretty short because I'm on my phone. We should have a more in depth discussion about this!
