### ISSUE TITLE
Rejected watchQuery promise is uncatchable

### ISSUE THREAD

**Issue by jamiter** [apollostack/apollo-client#891]
**Intended outcome:**
I was trying to use `watchQuery` and used an `error` handler when subscribing to updates on the returned observer:

```js
const observer = client.watchQuery({ /* options, no interval */ });

observer.subscribe({
  error: (err) => handleError(err)
})
```

I expected this to handle the error without any issues.

**Actual outcome:**
When the underlying query fails it correctly calls the error handler but also prints this in my console:

<img width="588" alt="screen shot 2016-11-08 at 16 57 18" src="https://cloud.githubusercontent.com/assets/1563874/20106179/8aa5a18a-a5d4-11e6-8796-dfbdcc5cfac6.png">    

**Reproduction:**
Subscribe on an observer that was returned by `.watchQuery` and make it fail (by throwing an error in your resolver on the server for example).

**Extra information**
There is no way to catch the error because `watchQuery` handles the query internally and doesn't return the promise anywhere.

The promise seems to be rejected here: https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L959-L973

**Comment by helfer** [comment]
thanks for reporting this. It's due to two different code paths (watchQuery and refetch) being slightly different. I think we could just suppress the warning here by catching the error. Do you have time to try it in your app and make a quick PR? https://github.com/apollostack/apollo-client/blob/0a985dca17c82f3fef4651c214c0d606e9c609b5/src/core/QueryManager.ts#L630

**Comment by jamiter** [comment]
@helfer, I created a PR for this. Could you have a look?
