### ISSUE TITLE
Integrate with other options for client-side data management

### ISSUE THREAD

**Issue by ansarizafar** [apollostack/apollo-client#92]
@stubailo check this [Freezer](https://github.com/arqex/freezer)

**Comment by helfer** [comment]
This looks interesting - especially because it has bindings for the Redux devtools - but I'm a bit concerned by the fact that it is basically written by one person and has less than 100 commits. Might be worth considering once it's more mature though. Swapping out the store at a later point shouldn't be too hard, I believe. @stubailo correct me if I'm wrong.

**Comment by stubailo** [comment]
Hmm, more and more I'm thinking building on Redux is one of our main advantages, since it's something people are really excited about. But in the future it would be cool to be able to integrate with all kinds of reactive backends, as long as we can apply our Redux reducers and actions to it.

**Comment by stubailo** [comment]
Other things to think about for this are RxJS, MobX, Tracker, etc.

**Comment by stubailo** [comment]
Relevant: #149 will let you integrate with RxJS

**Comment by helfer** [comment]
We're going to abstract the store and make it a public API, which should let people integrate with whatever they want.
