### ISSUE TITLE
Don't treat `id` as a special field unless instructed to do so

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#93]
Right now, the `id` field on an object is treated as a globally unique ID no matter what. I think this could cause serious issues for backends where the `id` property is not unique across types.

It's probably worth hiding this feature behind a flag somehow so that you can turn it on if you have a relay-like backend, and think about whether we want to handle non-unique IDs, or just build the Apollo Server to make it super easy to use these unique IDs.

@helfer do you think the Relay node spec is something that would be easy to build into the server? One more option is to make the client work with (id, typename) pairs, and not assume `id` is unique across all objects.

**Comment by helfer** [comment]
It wouldn't be too hard to build the Relay spec into the server. What I would propose is to add a _id field which defaults to 'id', but can be overridden with a resolve function on the type. If no custom _id resolve function is available and 'id' is not defined on that type, either null could be returned, or a hash could be generated. Although the hash could be a bad idea because it might not be unique in every application, so it's probably best to return null.

The one thing I'd rather not do is go off on our own with this one, but given that Relay requires the id field there might be a chance that the graphql-js folks would consider adding it to the spec and the reference implementation.

**Comment by stubailo** [comment]
Yeah I think making it really easy to follow the node spec on the server is the way to go. So I won't go to too much trouble to make non-unique IDs work well.

**Comment by helfer** [comment]
How do you feel about requiring people to use a server that's not spec compliant? My intuition is that we should stay compatible with the GraphQL reference implementation and spec if at all possible.

**Comment by stubailo** [comment]
Yeah I agree - I'm saying that you either conform to the relay spec and get nice refetching, or you don't and then you just turn that feature off. Just saying it's not worth having a third option where you don't use the relay node spec and still expect IDs to work nicely.

**Comment by helfer** [comment]
I agree, anything else doesn't make sense.

**Comment by stubailo** [comment]
Hmm, one awkward part to this is that this config needs to apply to the apolloReducer, since that's the thing that normalizes objects to put in the store. So if we want to have different ways of normalizing objects, it's not enough to have configuration in the client. Perhaps the API for adding a reducer needs to change. So instead of the current situation:

```js
import { createStore, combineReducers } from 'redux';
import { ApolloClient, apolloReducer } from 'apollo-client';
import { todoReducer, userReducer } from './reducers';

const store = createStore(
  combineReducers({
    todos: todoReducer,
    users: userReducer,
    apollo: apolloReducer,
  })
});

const client = new ApolloClient({ store });

client.store.getState();
```

We would instead do:


```js
import { createStore, combineReducers } from 'redux';
import { ApolloClient, apolloReducer } from 'apollo-client';
import { todoReducer, userReducer } from './reducers';

const client = new ApolloClient({ store });

const store = createStore(
  combineReducers({
    todos: todoReducer,
    users: userReducer,
    apollo: client.reducer,
  })
});

client.store.getState();
```

@jbaxleyiii @johnthepink how do we feel about such an API change, where the reducer is created by the client, taking into account the options passed into that client?

**Comment by stubailo** [comment]
One more option is to pass options into the `apolloReducer`, so like:

```js
import { createApolloReducer } from 'apollo-client';

createApolloReducer({
  objectIdField: 'id',
});

...
```

**Comment by jbaxleyiii** [comment]
@stubailo I think we need an API change, but I'm not sure what is best yet though. In the migration of our app we are running into somewhat of a race condition.

Typically in large scale redux apps, you have many reducers, then create the store where you initialize your app (i.e. the router if using react-router, or the root component). You do this by passing the store to redux's `Provider` component.

A few options I'm thinking through right now:

1. create the client in the file where the store gets initialized and export it
2. create the generic apollo store then rebuild the store by recombining the reducers where you would traditionally combine them and pass the store to the provider

The race conditions stems from middleware / sagas being run on the initial store creation (which runs through them for an error check if I'm not mistaken) but the client hasn't been created yet since it requires the store.

If the user isn't using Redux elsewhere, its a non issue. I'm working on a react-apollo bindings right now and part of that was to create a `Provider` like component that the client can be bound to and called via (much like dispatch with react-redux). I'm still not sure all the way though.

cc @johnthepink

**Comment by stubailo** [comment]
OK what about this:

1. `new ApolloClient` doesn't create a Redux store immediately.
1. If you are using your own store:
  1. You can get a reducer from it with client.reducer() which applies the config you passed to the constructor
  1. You initialize the store, and pass ApolloClient as a middleware
1. If you don't have your own store:
  1. When you first call anything on ApolloClient that needs the store, like `query`, it initializes the store


This gives you plenty of time between instantiating the client, and calling `query` for the first time, to initialize your store.

**Comment by jbaxleyiii** [comment]
@stubalio I think in practice that would work great!

**Comment by stubailo** [comment]
Any objections to this? If not, going to implement that right now.

**Comment by jbaxleyiii** [comment]
@stubailo none from me! Excited to see what these changes look like!

**Comment by stubailo** [comment]
@jbaxleyiii one thing that was buried in there is that I think a middleware is a better approach than `setStore`, does that sound good to you as well?

**Comment by jbaxleyiii** [comment]
@stubailo yep, it's more idiomatic with redux and doesn't expose an API that people not using redux might be confused by :tada:

**Comment by johnthepink** [comment]
Sounds good to me!

**Comment by lonyele** [comment]
I'm not really sure If questioning here is right or not, I think It is related.
From graphiql, there is no problem at all querying including id field with same value
```
[
      {
        "id": "123",
        "name": "John Smith"
      },
      {
        "id": "123",
        "name": "Sara Smith"
      },
      {
        "id": "123",
        "name": "Budd Deey"
      }
    ]
```
However with apollo-client, I get same amount of arrays but the values are same with the first array
```
[
      {
        "id": "123",
        "name": "John Smith"
      },
      {
        "id": "123",
        "name": "John Smith"
      },
      {
        "id": "123",
        "name": "John Smith"
      }
    ]
```
I'm now testing so I wouldn't use same value for id in real situation, though It gave me some frustrating time because of this weird behaviour. So this is intended right?
