### ISSUE TITLE
GraphQL syntax highlight

### ISSUE THREAD

**Issue by nlhkh** [apollostack/apollo-client#932]
Do you plan to support having queries in separate files?

The reason is we can have syntax highlight, and possibly type checking for queries.

**Comment by helfer** [comment]
@nlhkh you can probably already do this with a webpack loader. The reason we use the `gql` tag everywhere is because that will make it easy to highlight syntax even when it's not in a separate file.

But in any case, this question isn't really related to apollo-client, so I will close the issue. If you really want, maybe you can ask the question here: https://github.com/apollostack/eslint-plugin-graphql

**Comment by stubailo** [comment]
By the way, here are directions for putting your queries in a separate file: http://dev.apollodata.com/react/webpack.html

**Comment by nlhkh** [comment]
Many thanks :)
