### ISSUE TITLE
Investigate having a default dataIdFromObject

### ISSUE THREAD

**Issue by dburles** [apollostack/apollo-client#937]
I have an in memory array of objects containing unique `id` fields and noticed that the default IdGetter function doesn't seem to function.

Adding `dataIdFromObject: o => o.id,` as an option when instantiating ApolloClient solves the problem (as expected).

Also [the docs are a little unclear on the default behavior](http://dev.apollodata.com/react/cache-updates.html#dataIdFromObject), it reads as though `__typename + id` is the default. (See the note that states "Note: in 0.5.x, this is the default behavior")

Edit: I'm using apollo-client 0.5.5

**Comment by stubailo** [comment]
Oh. The default behavior is to add `__typename` to all queries. I heard this misconception recently from somewhere else and now I realize where it came from.

Basically, we can't have a default ID getter because people do all kinds of weird stuff with `id` fields and it would be surprising if we had a default that caused people to get seemingly incorrect data.

Perhaps one reasonable default would be to use an `__id` field if it is present, since that seems to be one possible proposal for standardizing IDs in GraphQL: https://github.com/facebook/graphql/pull/232

In the meanwhile, would you mind sending a PR to the docs to make it clear that no `dataIdFromObject` is set by default, and so no normalization happens until one is provided?

**Comment by dburles** [comment]
Thanks for clearing that up, I see now it's not a default `dataIdFromObject` function but rather the `__typename` is now available on the `result` by default, gotcha!

I'll take a look at what I can do to clear that up in the docs.

**Comment by dburles** [comment]
Perhaps that section on adding typename could simply be removed now?

**Comment by helfer** [comment]
@dburles can you link to which `__typename` section you mean? I want to say "yes", but I'm not 100% sure there's only one section about `__typename` in our docs.

Also closing this, since it's a docs issue now, no longer a client issue.

**Comment by dburles** [comment]
@helfer This section here http://dev.apollodata.com/react/cache-updates.html#dataIdFromObject

**Comment by helfer** [comment]
@dburles thanks! I've removed it.
