### ISSUE TITLE
Update cache of nested object after mutation when it's part of array

### ISSUE THREAD

**Issue by DimitryKislichenko** [apollostack/apollo-client#989]
In following [article](https://dev-blog.apollodata.com/building-a-graphql-store-from-first-principles-413e19ea65b4#.lgcmcqpr9), Sashko has described how caching works, and how nested objects are denormalized for caching, but is there a reason, why arrays of nested objects are not denormalized the same way?

Please consider follow query:

    query getBooking(
       $id: ID!
    ) {
       booking(id: $id) {
          id
          passengers {
             ...passenger
          }
       }
    }

    fragment passenger on Passenger {
       id
       firstName
    }

If at some point, I'll decide to update a single passenger, the only way to update cache is to do that over updateQueries, even every passenger has it's own unique ID.

**Comment by helfer** [comment]
@DimitryKislichenko if you update a single passenger's data, but not the identity of the elements in the array you can do that via the ID, and you don't even need `updateQuery`. Have you tried it?

**Comment by DimitryKislichenko** [comment]
@helfer, that's behaviour that I expected, but for some reason it doesn't work for arrays. That's why I've used updateQuery. 

Here is how I setup my client:

    const client = new ApolloClient({
        networkInterface,
        dateIdFromObject: o => o.id,
    });

So, you think that it should for array of objects and update cache of the object automatically, and that's probably my fault?

**Comment by helfer** [comment]
@DimitryKislichenko I'd be very surprised if it didn't work for arrays. Can you try with the simplest possible example and see if it still doesn't work?

**Comment by Dattaya** [comment]
I tried and it worked. 
I don't know if it was real code, but I've spotted one mistake: `dateIdFromObject` should be `dataIdFromObject`.

**Comment by calebmer** [comment]
Good catch @Dattaya on the `dateIdFromObject `. @DimitryKislichenko you may also want to confirm that you are requesting the `id` in your mutation as well as in your client.

I’m going to close because this is a functionality that we definitely test for, but if it’s still not working for you @DimitryKislichenko after looking at our suggestions then that’s definitely not a good sign!

Let us know if it still doesn’t work @DimitryKislichenko and please provide a small app reproducing the error so we can quickly fix the bug :+1:
