### ISSUE TITLE
Question about fragments and graphql-tag/loader

### ISSUE THREAD

**Issue by yurigenin** [apollostack/apollo-client#994]
The recent change to deprecate specifying fragments in options of a query raises the question about using graphql-tag/loader. Currently in my app I save both queries and fragments in separate files (.gql) and use a webpack loader (graphql-tag/loader) to preload them into a bundle. If from now on I have to reference fragments in a query using ${...} notation this will definitely break, won't it? This will force me to abondon storing fragments separately and always have them embedded into a query. Is there something I'm missing?

**Comment by helfer** [comment]
🤔 good question!

@tmeasday @stubailo Is there also an alternative way for defining fragments with graphql-tag?

**Comment by tmeasday** [comment]
Unless there is some way to `require` inside a `.graphql` file?

Perhaps we need to some utility to attach a fragment to a document after the fact?

```js
import myQuery from './myQuery.graphql';

const fullQuery = attachFragment(myQuery, FooComponent.fragments.barFragment);
```

I'm not sure if it's a good thing to have an incomplete `myQuery.graphql` in this scenario, and rely on the consumer to attach the fragment each time. If `myQuery` is referencing `FooBarFragment`, then you would need to run the `attachFragment` any time you use it, in which case it'd be better for `myQuery.graphql` to just do the attaching somehow (cf `require`-ing above).

**Comment by stubailo** [comment]
Hmm, I'll admit that we didn't think of this when making the change, although I still think it was a good change to make. I think having some way to import fragments is the way to go, and I can imagine something extremely clever:

```graphql
query myQuery {
  todos {
    name
    ...TodosFields @import(from: "../somewhere")
  }
}
```

The way Facebook handles this is by actually merging all `.graphql` files into one so that all queries and fragments are in one document, but I don't know if that fits the JS/Webpack mindset where things should be modular and declare dependencies explicitly?

Open to either solution, either way let's have this discussion at graphql-tag since I think Apollo Client shouldn't deal with fragments via options anymore: https://github.com/apollostack/graphql-tag

**Comment by wangyun** [comment]
My current workaround is importing file content of .graphql file using raw-loader, and use it like this:
`
const myQuery = gql`
  ${myQuery}
  ${fragments}
`;
`
